### PR TITLE
size optimisation

### PR DESCRIPTION
**Pull request by peterferrie**
needs heavy testing first

### CODE REVIEW

**Comment by peterferrie** [comment]
thank you, I have fixed the defects that you identified and updated the PR.
Regarding the TEXT charset, is it different behavior from the original?

**Comment by mist64** [comment]
Yes, without your change, it starts in GRAPHICS, with your change, it starts in TEXT.

**Comment by peterferrie** [comment]
> Yes, without your change, it starts in GRAPHICS, with your change, it starts
> in TEXT.

I see it now.  I have fixed it.

**Comment by mist64** [comment]
The latest change starts in graphics mode, but ` PRINT CHR$(14)` and `PRINT CHR$(142)` should switch between TEXT and GRAPHICS; but they both switch to TEXT. An `ASL` in `cmd_graphics` fixes this. (And the caller in the init code has to do `LDA #$80`.

**Comment by peterferrie** [comment]
> The latest change starts in graphics mode, but ` PRINT CHR$(14)` and `PRINT
> CHR$(142)` should switch between TEXT and GRAPHICS; but they both switch to
> TEXT. An `ASL` in `cmd_graphics` fixes this. (And the caller in the init
> code has to do `LDA #$80`.

Yes, I see it.  I've added a comment regarding the reuse of the LDA
#$90 for the purpose.

**Comment by mist64** [comment]
Now you still have the same problem with `MODE_enable`, which is called with an unpredictable value in `A`, so effectively charset switching (Cmdr+Shift) is disabled start, but it should be enabled.

**Comment by mist64** [comment]
Oh, and I pushed a tiny change with just comments in the meantime, so your patch needs to be rebased. Sorry. :(

**Comment by peterferrie** [comment]
> Oh, and I pushed a tiny change with just comments in the meantime, so your
> patch needs to be rebased. Sorry. :(

That's fine.  I've resubmitted.

**Pull request closed without merging**
